import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import DateContext from '../dateContext/DateContext'
const inter = Roboto_Serif({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DateContext>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </DateContext>
  );
}
